apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging-roundtrip
labels:
- pairs:
    app: roundtrip
    app.kubernetes.io/component: roundtrip
    app.kubernetes.io/instance: roundtrip
    app.kubernetes.io/name: roundtrip
    app.kubernetes.io/part-of: roundtrip
configMapGenerator:
- name: roundtrip-config
  files:
  - config/config.yaml
resources:
- deployment.yaml
- metrics.yaml
- namespace.yaml
- rbac.yaml
- route.yaml
- service.yaml
