apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging-roundtrip
commonAnnotations:
  app.openshift.io/vcs-ref: main
  app.openshift.io/vcs-uri: https://github.com/xperimental/logging-roundtrip.git
  openshift.io/generated-by: OpenShiftWebConsole
labels:
- pairs:
    app: roundtrip
    app.kubernetes.io/component: roundtrip
    app.kubernetes.io/instance: roundtrip
    app.kubernetes.io/name: roundtrip
    app.kubernetes.io/part-of: roundtrip
configMapGenerator:
- name: roundtrip-config
  files:
  - config/config.yaml
resources:
- buildconfig.yaml
- deployment.yaml
- imagestream.yaml
- namespace.yaml
- rbac.yaml
- route.yaml
- secret.yaml
- service.yaml
