apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: logging-roundtrip
spec:
  selector:
    matchLabels:
      app: roundtrip
  endpoints:
  - port: web
    scheme: http
    path: /metrics
