apiVersion: v1
kind: ServiceAccount
metadata:
  name: roundtrip
---
apiVersion: v1
kind: Secret
metadata:
  name: roundtrip-sa-token
  annotations:
    kubernetes.io/service-account.name: roundtrip
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roundtrip-read-logs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-logging-application-view
subjects:
- kind: ServiceAccount
  name: roundtrip
