services:
  loki:
    image: docker.io/grafana/loki
    ports:
    - "3100:3100"
  promtail:
    image: docker.io/grafana/promtail
    links:
    - loki
    command:
    - "-config.file"
    - "/config/promtail.yaml"
    ports:
    - "9080:9080"
    volumes:
    - "./config:/config:ro"
    - "./data/:/data"
